
- name: Create NFS directory
  file:
    path: "{{ nfs_data_dir }}"
    state: directory
    mode: '0777'

- name: Install NFS server packages
  apt:
    name: nfs-kernel-server
    state: present

- name: Generate /etc/exports
  template:
    src: etc/exports.j2
    dest: /etc/exports

- name: Restart NFS server
  service:
    name: nfs-kernel-server
    state: restarted
